### ISSUE TITLE
optimize soggy planet rendering

### ISSUE THREAD

**Issue by ghost** [cosmicplayground/cosmicplayground#56]
[soggy planet](https://www.cosmicplayground.org/soggy-planet) shows up to 13 elevations below sea level along with lights at nighttime, in addition to the 3 elevations above sea level I implemented a while ago. It works as intended but I'm not happy with the performance, especially when zoomed out. (might not drop frames depending on your card) The [previous version of the map](https://www.cosmicplayground.org/deep-breath) doesn't have the same perf problems because it uses 15 fewer images. (13 elevations, 1 of night lights, and 1 to darken everything at night)

It uses [PixiJS](https://pixijs.com/) (though there's a DOM renderer that performs worse, press `ctrl+Backtick`) and a simplistic rendering strategy: there's just a bunch of large images that get faded in and out over each other. 

I'm wondering what could be done to improve performance -- maybe shaders and combine images? It'd be my first time using shaders. The images with below sea level elevations are very simple, just a single color on each. ([example](https://github.com/cosmicplayground/cosmicplayground/blob/main/src/static/assets/earth/shore_1.png)) A [`Filter`](https://pixijs.download/release/docs/PIXI.Filter.html) (which uses a shader) similar to [the builtin `ColorMatrixFilter`](https://pixijs.io/examples/#/filters-basic/color-matrix.js) may be what I'm aftrer?

**Comment by ghost** [comment]
it crashes on all 3 phones and 1 tablet that ive tried :[

**Comment by ryanatkn** [comment]
working on this in #65, used ChatGPT to get a nudge in the right direction (was my first time solving a programming problem with an AI)

**Comment by ryanatkn** [comment]
this could be still be improved, using the same technique for the above-sea-level parts
